"""initial schema

Revision ID: 12b819c5d537
Revises: 
Create Date: 2026-08-29 22:06:35.302254

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '12b819c5d537'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('min_cohort_threshold', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SEEDING', 'LIVE', name='communitystatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('community_id')
    )
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_slug'), ['slug'], unique=True)

    op.create_table('place_ref',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cached_lat', sa.Float(), nullable=True),
    sa.Column('cached_lng', sa.Float(), nullable=True),
    sa.Column('coords_cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('community_aggregate',
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('noise_epsilon', sa.Float(), nullable=True),
    sa.CheckConstraint('cohort_size >= 0', name='ck_community_aggregate_cohort_size_non_negative'),
    sa.ForeignKeyConstraint(['community_id'], ['community.community_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['place_ref.place_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('aggregate_id')
    )
    with op.batch_alter_table('community_aggregate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_aggregate_community_id'), ['community_id'], unique=False)

    op.create_table('community_membership',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('FOUNDER', 'JOINER', name='tier', native_enum=False, length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.community_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id')
    )
    with op.batch_alter_table('community_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_membership_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_membership_user_id'), ['user_id'], unique=False)

    op.create_table('consent_record',
    sa.Column('consent_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Enum('DIRECT_CURATION', 'GOOGLE_IMPORT_ONE_TIME', 'GOOGLE_IMPORT_TIME_BOUNDED', name='consentscope', native_enum=False, length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id')
    )
    with op.batch_alter_table('consent_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_record_user_id'), ['user_id'], unique=False)

    op.create_table('facet',
    sa.Column('facet_id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value_type', sa.Enum('NUMERIC', 'ORDINAL', 'BOOLEAN', 'TEXT', name='facetvaluetype', native_enum=False, length=16), nullable=False),
    sa.Column('scale_min', sa.Float(), nullable=True),
    sa.Column('scale_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.community_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('facet_id')
    )
    with op.batch_alter_table('facet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facet_community_id'), ['community_id'], unique=False)

    op.create_table('facet_stat',
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('facet_id', sa.Uuid(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aggregate_id'], ['community_aggregate.aggregate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facet_id'], ['facet.facet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aggregate_id', 'facet_id')
    )
    op.create_table('google_import_job',
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consent_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('INITIATED', 'PENDING', 'COMPLETE', 'FAILED', 'EXPIRED', name='importjobstate', native_enum=False, length=16), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_url_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consent_record.consent_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('google_import_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_import_job_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_import_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_import_job_user_id'))

    op.drop_table('google_import_job')
    op.drop_table('facet_stat')
    with op.batch_alter_table('facet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facet_community_id'))

    op.drop_table('facet')
    with op.batch_alter_table('consent_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_record_user_id'))

    op.drop_table('consent_record')
    with op.batch_alter_table('community_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_membership_community_id'))

    op.drop_table('community_membership')
    with op.batch_alter_table('community_aggregate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_aggregate_community_id'))

    op.drop_table('community_aggregate')
    op.drop_table('user')
    op.drop_table('place_ref')
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_slug'))

    op.drop_table('community')
    # ### end Alembic commands ###
