"""identity link and session token

Revision ID: 6b0a8c8f0ed0
Revises: 12b819c5d537
Create Date: 2026-09-01 20:32:10.163103

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6b0a8c8f0ed0'
down_revision: str | None = '12b819c5d537'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_link',
    sa.Column('subject_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_hash')
    )
    with op.batch_alter_table('identity_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_link_user_id'), ['user_id'], unique=False)

    op.create_table('session_token',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('session_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_token_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_token_user_id'))

    op.drop_table('session_token')
    with op.batch_alter_table('identity_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_link_user_id'))

    op.drop_table('identity_link')
    # ### end Alembic commands ###
